language: java
sudo: required
services:
  - docker
env:
  - SERVICE_GROUP=avvero SERVICE_NAME=crools SERVICE_VERSION=0.1
script:
  - ./gradlew build
  - ./gradlew installDist
  - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD hub.docker.com
  - docker build --pull -t $SERVICE_GROUP/$SERVICE_NAME:$SERVICE_VERSION .
  - docker push $SERVICE_GROUP/$SERVICE_NAME:$SERVICE_VERSION
  - docker build --pull -t $SERVICE_GROUP/$SERVICE_NAME:latest .
  - docker push $SERVICE_GROUP/$SERVICE_NAME:latest